In [1]:
import wave
import numpy as np
from scipy.io.wavfile import read

In [2]:
RATE = 44100
EXTEND = 441
SCALE = 12

In [3]:
# Read file to get buffer                                                                                               
ifile = read("test.wav")
#samples = ifile.getnframes()
audio = np.array(ifile[1])


In [4]:
unscale = np.round(audio*SCALE,2)
unscale[0]

0.4

In [5]:
npFinalOutput = np.zeros([59,29])
            
k=0
for i in range(59):
    for j in range(29):
        npFinalOutput[i][j] = np.float32(unscale[k])
        k = k+EXTEND;


npFinalOutput = np.float32(npFinalOutput)
print(npFinalOutput)
npFinalOutput.shape

[[0.4 0.1 0.3 ... 0.5 0.4 0.2]
 [0.5 0.1 0.4 ... 0.3 0.3 0.1]
 [0.2 0.4 0.5 ... 0.5 0.4 0.3]
 ...
 [0.2 0.2 0.4 ... 0.3 0.3 0.3]
 [0.5 0.2 0.1 ... 0.2 0.2 0.3]
 [0.3 0.1 0.5 ... 0.5 0.1 0.2]]


(59, 29)

In [6]:
npTestArr = np.genfromtxt("./Naks_Tree.csv", delimiter=',') 
npTestArr = np.delete(npTestArr,0,0)

In [7]:
npTestArr = np.float32(npTestArr)
npTestArr

array([[0.4, 0.1, 0.3, ..., 0.5, 0.4, 0.2],
       [0.5, 0.1, 0.4, ..., 0.3, 0.3, 0.1],
       [0.2, 0.4, 0.5, ..., 0.5, 0.4, 0.3],
       ...,
       [0.2, 0.2, 0.4, ..., 0.3, 0.3, 0.3],
       [0.5, 0.2, 0.1, ..., 0.2, 0.2, 0.3],
       [0.3, 0.1, 0.5, ..., 0.5, 0.1, 0.2]], dtype=float32)

In [8]:
npFinalOutput

array([[0.4, 0.1, 0.3, ..., 0.5, 0.4, 0.2],
       [0.5, 0.1, 0.4, ..., 0.3, 0.3, 0.1],
       [0.2, 0.4, 0.5, ..., 0.5, 0.4, 0.3],
       ...,
       [0.2, 0.2, 0.4, ..., 0.3, 0.3, 0.3],
       [0.5, 0.2, 0.1, ..., 0.2, 0.2, 0.3],
       [0.3, 0.1, 0.5, ..., 0.5, 0.1, 0.2]], dtype=float32)

In [9]:
for i in range(59):
    for j in range(29):
        if npFinalOutput[i][j] != npTestArr[i][j] :
            print(i,j)