In [1]:
import wave
import numpy as np
from scipy.io.wavfile import read

from PIL import Image
import cv2

In [2]:
RATE = 44100
EXTEND = 1
SCALE = 255

In [3]:
ifile = read("test.wav")

audio = np.array(ifile[1])

In [4]:
unscale = np.float32(audio*SCALE)
unscale[172165]

255.0

In [5]:
npFinalOutput = np.zeros([997,997])
            
k=0
for i in range(997):
    for j in range(997):
        npFinalOutput[i][j] = np.uint8(unscale[k])
        k = k+EXTEND;


npFinalOutput = np.uint8(npFinalOutput)
print(npFinalOutput)
npFinalOutput.shape

[[16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 ...
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]]


(997, 997)

In [6]:
bwImage = Image.open('BandW_CancerImg.jpg')
# print(bwImage.format)
# print(bwImage.size)
# print(bwImage.mode)
npBWImage = np.uint8(bwImage)
npBWImage.shape

(997, 997)

In [7]:
npTestArr = np.uint8(npBWImage)
npTestArr

array([[16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       ...,
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16]], dtype=uint8)

In [8]:
npFinalOutput

array([[16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       ...,
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16],
       [16, 16, 16, ..., 16, 16, 16]], dtype=uint8)

In [9]:
for i in range(997):
    for j in range(997):
        if npFinalOutput[i][j] != npTestArr[i][j] :
            print(npFinalOutput[i][j],npTestArr[i][j])

In [10]:
bwImage = Image.fromarray(npFinalOutput)
bwImage.save("finalOutputImage.jpg")
# summarize some details about the image
print(bwImage.format)
print(bwImage.size)
print(bwImage.mode)


None
(997, 997)
L


In [11]:
finalOutputImage = cv2.imread('finalOutputImage.jpg')
cv2.startWindowThread()
cv2.namedWindow('Final Output Image')
cv2.moveWindow('Final Output Image',50,50)
cv2.imshow('Final Output Image',finalOutputImage)
cv2.waitKey(5000)
cv2.destroyAllWindows()